### ISSUE TITLE
[BUG] Mobile navbar window transparent, covers other menu

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#283] opened 2024-09-24 02:55 UTC
## Issue Overview

Issue as shown on the screenshot below

<img width="228" alt="image" src="https://github.com/user-attachments/assets/27b153ba-425e-481b-bdf4-ae768e58acde">

## Proposed Solutions or Ideas

- Check the corresponding style.

**Comment by od-hunter** [comment] 2024-09-24 05:12
U

**Comment by vickiddev** [comment] 2024-09-25 04:12
hello @metalboyrick @Nadai2010 i'm a frontend dev and would love to work on this issue and be able to contribute to this repo please :) give me this chance to do this one

**Comment by martinvibes** [comment] 2024-09-25 17:21
hello @dmirgaleev i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by Ayoazeez26** [comment] 2024-09-26 07:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a frontend developer with 6 years experience building applications

### How I plan on tackling this issue
Fix the mobile navbar and make sure it doesn't cover other menu

**Comment by Dprof-in-tech** [comment] 2024-09-26 07:51
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello, i am Dprof-in-tech, an experienced Full Stack Blockchain Developer and  I am excited to contribute my skills to this project in this ODHACK 8. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Rust and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 34 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.
My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we begin ODHACK 8, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.
Below is a link to my OnlyDust public profile.
https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
I will investigate the mobile navbar styling:
I will inspect the CSS and layout for the mobile version of the navbar. This likely involves looking into z-index values, background colors, or transparency settings that may be causing the navbar to overlap with other menus incorrectly.
I will identify the root cause of the transparency:
I will focus on isolating the CSS responsible for the transparency issue. This could be due to missing background styles, incorrect z-index layers, or conflicting styles with other components.
I will adjust the z-index and background styles:
If the issue is related to the z-index, I will modify the stacking order so that the navbar doesn’t interfere with other elements on the page.
I will also ensure the navbar has the appropriate background color (non-transparent) and padding to make it behave as expected on mobile devices.
I will test across different screen sizes:
I will test the fix on various mobile devices and screen sizes to ensure that the issue is resolved for all users, regardless of their device.
I will capture and report the fix:
Once resolved, I will submit a screenshot showing the correct behavior of the navbar and ensure that no new issues are introduced by the change.


My estimated time of delivery is within a day and i would be sure to follow the rules of contributing to speedrun scaffold stark.

**Comment by martinvibes** [comment] 2024-09-26 07:54
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hi I would love to work on this issue

**Comment by Luluameh** [comment] 2024-09-26 08:33
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have a strong background in front-end web development, specializing in responsive design and UI/UX optimization. I have worked with JavaScript, TypeScript, and modern CSS frameworks to create mobile-first, user-friendly applications. My experience includes debugging style-related issues, optimizing mobile interfaces, and ensuring that components behave correctly across different screen sizes.

Through my experience working with responsive layouts and CSS-specific issues, I can leverage these skills to address the transparency problem in the mobile navbar efficiently. I am comfortable identifying and fixing style issues by inspecting elements, adjusting z-index, or modifying other CSS properties that could be causing the overlap or transparency.



### How I plan on tackling this issue
To approach this issue, I would take the following steps:

Analyze the Existing Code: I would begin by inspecting the mobile navbar's current styles and its relationship with the rest of the menu. I would pay particular attention to the transparency and positioning styles (e.g., z-index, position, opacity, etc.) that may be causing the issue.

Identify the Problem: Based on the analysis, I would pinpoint the exact cause of the transparency issue. This could involve a missing background color, incorrect z-index, or improperly positioned elements. I would also verify if the navbar is responsive across various devices or screen sizes to identify any layout inconsistencies.

Fix the Style Issue: Once identified, I would modify the CSS or apply relevant fixes. This could involve adding or correcting background colors, adjusting the z-index to ensure the navbar does not overlay other elements, or modifying any CSS properties that impact its visibility or interaction.

Test the Fix: After making the changes, I would test the fix across different devices and screen sizes, ensuring the navbar functions correctly and no longer covers the other menu or appears transparent. I would use browser developer tools to simulate different mobile views.

Collaborate with the Team: If necessary, I would communicate with the design team to ensure that the changes align with the intended user experience and design requirements, especially regarding the mobile layout.

Document the Solution: Finally, I would document the fix in the issue tracker or repository, detailing the changes made to solve the problem. This will help other developers understand the solution and maintain consistency in future updates.

**Comment by melnikga** [comment] 2024-09-26 09:40
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Can I take this?

### How I plan on tackling this issue
My profile on OnlyDust: https://app.onlydust.com/u/melnikga

**Comment by omsant02** [comment] 2024-09-26 09:53
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am Om Santoshwar,
Final year btech UG at IIT Dhanbad,
i have a strong background in web development and blockchain development particularly in Ethereum and Starknet with 3 years of software development experience.

My Technical Skills-
Languages: Typescript, Javascript, Solidity, Rust, Cairo, C++
Frameworks and tools: Scaffold-eth/Stark, Nextjs, MERN, Ethersjs, Hardhat, Foundry, Openzeppelin contracts, Defi, AWS

Experience-
Participated in EthGlobal and other blockchain hackathons
Internships as Blockchain and Fullstack web developer

### How I plan on tackling this issue
i can see when we shrink the web page to mobile screen, the elements get messed up and is not looking good,
i will first move some elements which are side by side and make them one above the other so they gets fit into smaller screen,
also for the hamburger menu i will give a solid background color so that it will not get mixed up with other elements

**Comment by josephchimebuka** [comment] 2024-09-26 10:55
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hello, I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka.this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will ensure the bug is fixed in 2-4 days

**Comment by EnochScript** [comment] 2024-09-26 11:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am a frontend developer with expertise in JavaScript and react. This is my first time contributing to ODHack and I will like the opportunity to contribute to this project. I have good technical knowledge on JavaScript, CSS and CSS frameworks ; I have the ability to work under pressure and adapt quickly and these will help me to contribute effectively to solving diverse challenges.

### How I plan on tackling this issue
To solve this issue, I will:

a. Analyze the Existing CSS Code: . I will inspect the mobile navbar's styles like z-index, position and opacity that may be causing the issue.

b. Fix the Style Issue: Once the issue is identified after analyzing the code, I would modify the CSS or apply the necessary fixes. This could involve  adjusting the z-index to ensure the navbar does not overlay other elements, or modifying any CSS properties that impact its visibility, interaction or position.

c. Test the Fix: After making the changes, I would test the fix across different devices and screen sizes, ensuring the navbar functions correctly and no longer covers the other menu or appears transparent. I would use browser developer tools to simulate different mobile views.

d. Document the Solution: Finally, I would document the fix in the issue tracker or repository, detailing the changes made to solve the problem. This will help other developers understand the solution and maintain consistency in future updates.

**Comment by metalboyrick** [comment] 2024-09-26 12:12
all yours @omsant02

**Comment by omsant02** [comment] 2024-09-29 09:05
Hey @metalboyrick ,

I have raised a PR. Please review the code. Apart from fixing the main issue, I have also aligned the theme switcher and adjusted spacing.

**Closed** 2024-10-02 04:14 UTC
Labels: bug, good first issue, external-contributor, difficulty: easy, ODHack8
