### ISSUE TITLE
[CHORE] Replace `yarn deploy:reset` with `yarn deploy`, Create a `yarn deploy —no-reset`

### ISSUE THREAD

**Issue by metalboyrick** [Scaffold-Stark/scaffold-stark-2#285] opened 2024-09-24 03:20 UTC
## Issue Overview

We want to make the `yarn deploy:reset` behaviour the default one. Create a `yarn deploy —no-reset` if needed.

## Proposed Solutions or Ideas

- Update `package.json`

**Comment by jsandinoDev** [comment] 2024-09-24 05:35
Hi @metalboyrick  can I work on this?

**Comment by Nadai2010** [comment] 2024-09-24 07:16
Hello everyone, @jsandinoDev the Issues for the OD Hack will be assigned to each of you at the start, prepare your skills.

**Comment by pablomadrigal** [comment] 2024-09-26 07:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I’m Pablo Madrigal, I have 7+ years of experience working with React and NextJs. I’m pretty new in the web3 world, I just joined Dojo Coding a couple of weeks ago and have been learning a lot about Cairo and web3 development. Pretty excited to start contributing on Only Dust

### How I plan on tackling this issue
I'm going to modify package.json to change the default behavior of the deploy so it executes with the reset and create a new script for deploy without reset

**Comment by Luluameh** [comment] 2024-09-26 08:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have a strong background in full-stack development, with extensive experience in using JavaScript, TypeScript, and various package managers like Yarn and npm. I have worked on several projects involving script automation and DevOps workflows, where modifying and optimizing deployment scripts has been crucial. This experience includes working with build tools, managing deployment pipelines, and adjusting scripts for different environments.

My knowledge of configuring package.json scripts allows me to make the necessary changes to streamline workflows while maintaining clarity in commands. I can leverage this experience to improve the developer experience by making the deployment process smoother and ensuring clear documentation of new commands.

### How I plan on tackling this issue
To approach this problem, I would follow these steps:

Analyze the Current Setup: First, I would review the package.json file to understand the current scripts, specifically the yarn deploy:reset behavior. This would help ensure I know what the reset behavior involves and how it's currently being executed.

Update yarn deploy: I would modify the package.json script for yarn deploy so that it adopts the current behavior of yarn deploy:reset. This change would ensure that resetting becomes the default behavior, simplifying the deployment process.

Create yarn deploy --no-reset: Next, I would introduce the yarn deploy --no-reset option by adding a separate script in package.json that omits the reset functionality during deployment. This would provide flexibility for cases where developers want to deploy without resetting the environment.

Test Changes: I would thoroughly test both the updated yarn deploy command and the new yarn deploy --no-reset command to ensure they work as expected. This testing would include deploying in different environments (e.g., local, staging) to verify that the changes do not introduce any issues in the workflow.

Document the Changes: After implementing and testing the changes, I would update any documentation to clearly explain the new deployment process. This would ensure that other developers on the team are aware of the command changes and know how to use both yarn deploy and yarn deploy --no-reset appropriately.

**Comment by Jemiiah** [comment] 2024-09-26 08:53
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I would love to work on this issue 

### How I plan on tackling this issue
i plan to solve this issue with an ETA of 48 hours

**Comment by deeseeker** [comment] 2024-09-26 08:54
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
Hi, I'm Qudus Adeyemi, a frontend developer with 2 years of experience specializing in React, TypeScript, and JavaScript. In the previous OD Hackathon, I had the opportunity to contribute by improving the Starknet React documentation and developing a useWatchAssets hook for better wallet-tracking functionality. I enjoy learning new things and taking on challenges, and I see this issue as a valuable opportunity to further my knowledge of Web3 while contributing meaningfully to the Gostarkme project.

I estimate the task will take around 2-3 days to complete, and I'm eager to start and collaborate with the team!

### How I plan on tackling this issue
This is how I would tackle this issue:

Clone the project on my local machine and ensure it runs by following the provided documentation.
Try the proposed solution
Proceed to the setting up yarn deploy:reset and creating yarn deploy —no-reset if needed

In case where the proposed solution doesn't work, I will research a new solution and reiterate the process
Implement the fix based on my findings and knowledge.
Test thoroughly to ensure the issue is resolved.
Document the solution

**Comment by ScottyDavies** [comment] 2024-09-26 09:37
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I have experience in web development and DevOps, with experience in configuring package management tools like Yarn

### How I plan on tackling this issue
To tackle the issue, I would:

Modify package.json:
 Update the existing scripts to set yarn deploy:reset as the default behavior for the yarn deploy command.

Create New Script: 
If necessary, add a new script for yarn deploy --no-reset to preserve the original behavior without resetting.

Test Changes: 
Run both yarn deploy and yarn deploy --no-reset to ensure they function as intended.

Commit Changes:
 Document the updates in the commit message and push the changes for review.

**Comment by omsant02** [comment] 2024-09-26 10:21
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/speedrun-scaffold-stark).

### My background and how it can be leveraged
I am Om Santoshwar,
Final year btech UG at IIT Dhanbad,
i have a strong background in web development and blockchain development particularly in Ethereum and Starknet with 3 years of software development experience.

My Technical Skills-
Languages: Typescript, Javascript, Solidity, Rust, Cairo, C++
Frameworks and tools: Scaffold-eth/Stark, Nextjs, MERN, Ethersjs, Hardhat, Foundry, Openzeppelin contracts, Defi, AWS

Experience-
Participated in EthGlobal and other blockchain hackathons
Internships as Blockchain and Fullstack web developer

### How I plan on tackling this issue
this issue can be solve by changing the scripts in the deploy-wrapper file,
there we have to change the default to reset and make a new script for --no reset,

additionally need to make changes in pakage.json

**Comment by Nadai2010** [comment] 2024-09-26 14:47
All yours @Jemiiah

**Comment by jsandinoDev** [comment] 2024-09-26 14:50
Hi @Nadai2010  I comment in this issue 2 days ago and I thought I didn't have to apply by means of only dust by this message


<img width="949" alt="Screenshot 2024-09-26 at 8 49 32 AM" src="https://github.com/user-attachments/assets/d30226ed-d67a-45ab-bb78-998c0639e631">


Only applications through OnlyDust are valid?

**Comment by Nadai2010** [comment] 2024-09-26 14:57
Sorry @jsandinoDev  

The issues are not assigned by order, the team analyses all the devs that have submitted in all issue and decides, it is not fair to assign by order, some may even be bots or devs with no experience in home difficulty or type of integration.

It may be that new issues are added before the end of the Hack, we will take this into account.

**Comment by metalboyrick** [comment] 2024-10-02 11:01
Hi @Jemiiah , any updates on this issue?

**Closed** 2024-10-14 15:01 UTC
Labels: external-contributor, difficulty: medium, ODHack8
